CREATE TABLE ORAADM.INDEX_AUDIT
(
  OWNER         VARCHAR2(4000 BYTE),
  NAME_INDEX    VARCHAR2(4000 BYTE),
  OBJECT_ALIAS  VARCHAR2(4000 BYTE),
  OBJECT_TYPE   VARCHAR2(4000 BYTE),
  TIMESTAMP     DATE
)